-- Sample tickets seed (55 rows). Run after migrations. Separate from cloud_sql_seed_mock_tickets.sql.
-- Placeholder embedding [1,0,...,0] for pgvector(768); replace via embedding pipeline for real search.

INSERT INTO business_units (code, name) VALUES
    ('B1', 'Reservations Platform'),
    ('B2', 'Payments Platform'),
    ('B3', 'Identity & Access'),
    ('Default', 'Unmapped / default')
ON CONFLICT (code) DO NOTHING;

INSERT INTO tickets (
    jira_id, business_unit, ticket_type, summary, description, status, resolution,
    discussion, created_at, updated_at, embedding, raw_json
) VALUES
    (
        'SMP-5001',
        'B1',
        'BUG',
        'Phishing campaign targeting finance mailboxes',
        'Details for Phishing campaign targeting finance mailboxes. Tracked under sample seed SMP. Ticket index 1.',
        'Open',
        NULL,
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-01-15T09:00:00',
        timestamptz '2024-01-16T09:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5002',
        'B1',
        'TASK',
        'EDR false positive blocking legitimate installer',
        'Details for EDR false positive blocking legitimate installer. Tracked under sample seed SMP. Ticket index 2.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-01-17T10:00:00',
        timestamptz '2024-01-19T10:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5003',
        'B2',
        'STORY',
        'VPN split tunnel leak on macOS 14.2',
        'Details for VPN split tunnel leak on macOS 14.2. Tracked under sample seed SMP. Ticket index 3.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-01-19T11:00:00',
        timestamptz '2024-01-22T11:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5004',
        'B2',
        'INCIDENT',
        'SIEM ingestion lag exceeding 15 minutes',
        'Details for SIEM ingestion lag exceeding 15 minutes. Tracked under sample seed SMP. Ticket index 4.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-01-21T12:00:00',
        timestamptz '2024-01-25T12:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5005',
        'B3',
        'BUG',
        'WAF rule blocking partner API callbacks',
        'Details for WAF rule blocking partner API callbacks. Tracked under sample seed SMP. Ticket index 5.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-01-23T13:00:00',
        timestamptz '2024-01-28T13:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5006',
        'B1',
        'TASK',
        'MFA enrollment bypass in legacy SSO flow',
        'Details for MFA enrollment bypass in legacy SSO flow. Tracked under sample seed SMP. Ticket index 6.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-01-25T14:00:00',
        timestamptz '2024-01-26T14:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5007',
        'B1',
        'STORY',
        'Container image with critical CVE in base layer',
        'Details for Container image with critical CVE in base layer. Tracked under sample seed SMP. Ticket index 7.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-01-27T15:00:00',
        timestamptz '2024-01-29T15:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5008',
        'B2',
        'INCIDENT',
        'Secrets scanner flagged committed .env fragment',
        'Details for Secrets scanner flagged committed .env fragment. Tracked under sample seed SMP. Ticket index 8.',
        'In Progress',
        NULL,
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-01-29T16:00:00',
        timestamptz '2024-02-01T16:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5009',
        'B2',
        'BUG',
        'DDoS mitigation triggered on edge POP',
        'Details for DDoS mitigation triggered on edge POP. Tracked under sample seed SMP. Ticket index 9.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-01-31T17:00:00',
        timestamptz '2024-02-04T17:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5010',
        'B3',
        'TASK',
        'Privileged account without quarterly access review',
        'Details for Privileged account without quarterly access review. Tracked under sample seed SMP. Ticket index 10.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-02-02T18:00:00',
        timestamptz '2024-02-07T18:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5011',
        'B1',
        'STORY',
        'CloudTrail log delivery failure to S3 bucket',
        'Details for CloudTrail log delivery failure to S3 bucket. Tracked under sample seed SMP. Ticket index 11.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-04T19:00:00',
        timestamptz '2024-02-05T19:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5012',
        'B1',
        'INCIDENT',
        'TLS 1.0 still enabled on internal load balancer',
        'Details for TLS 1.0 still enabled on internal load balancer. Tracked under sample seed SMP. Ticket index 12.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-02-06T20:00:00',
        timestamptz '2024-02-08T20:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5013',
        'B2',
        'BUG',
        'Ransomware simulation exercise follow-up tasks',
        'Details for Ransomware simulation exercise follow-up tasks. Tracked under sample seed SMP. Ticket index 13.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-08T09:00:00',
        timestamptz '2024-02-11T09:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5014',
        'B2',
        'TASK',
        'IAM policy allows s3:* on production bucket',
        'Details for IAM policy allows s3:* on production bucket. Tracked under sample seed SMP. Ticket index 14.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-10T10:00:00',
        timestamptz '2024-02-14T10:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5015',
        'B3',
        'STORY',
        'Endpoint encryption key escrow workflow broken',
        'Details for Endpoint encryption key escrow workflow broken. Tracked under sample seed SMP. Ticket index 15.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-02-12T11:00:00',
        timestamptz '2024-02-17T11:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5016',
        'B1',
        'INCIDENT',
        'SOC alert fatigue on duplicate correlation rules',
        'Details for SOC alert fatigue on duplicate correlation rules. Tracked under sample seed SMP. Ticket index 16.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-02-14T12:00:00',
        timestamptz '2024-02-15T12:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5017',
        'B1',
        'BUG',
        'Backup restore test failed for regional DB',
        'Details for Backup restore test failed for regional DB. Tracked under sample seed SMP. Ticket index 17.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-16T13:00:00',
        timestamptz '2024-02-18T13:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5018',
        'B2',
        'TASK',
        'OAuth token refresh race in mobile app',
        'Details for OAuth token refresh race in mobile app. Tracked under sample seed SMP. Ticket index 18.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-02-18T14:00:00',
        timestamptz '2024-02-21T14:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5019',
        'B2',
        'STORY',
        'Shadow IT SaaS discovered via CASB',
        'Details for Shadow IT SaaS discovered via CASB. Tracked under sample seed SMP. Ticket index 19.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-20T15:00:00',
        timestamptz '2024-02-24T15:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5020',
        'B3',
        'INCIDENT',
        'Kerberos clock skew causing auth failures',
        'Details for Kerberos clock skew causing auth failures. Tracked under sample seed SMP. Ticket index 20.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-22T16:00:00',
        timestamptz '2024-02-27T16:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5021',
        'B1',
        'BUG',
        'Firewall change request missing CAB approval',
        'Details for Firewall change request missing CAB approval. Tracked under sample seed SMP. Ticket index 21.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-02-24T17:00:00',
        timestamptz '2024-02-25T17:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5022',
        'B1',
        'TASK',
        'PAM session recording storage near capacity',
        'Details for PAM session recording storage near capacity. Tracked under sample seed SMP. Ticket index 22.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-02-26T18:00:00',
        timestamptz '2024-02-28T18:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5023',
        'B2',
        'STORY',
        'Email gateway quarantine delay for bulk mail',
        'Details for Email gateway quarantine delay for bulk mail. Tracked under sample seed SMP. Ticket index 23.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-02-28T19:00:00',
        timestamptz '2024-03-02T19:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5024',
        'B2',
        'INCIDENT',
        'Kubernetes API anonymous access misconfiguration',
        'Details for Kubernetes API anonymous access misconfiguration. Tracked under sample seed SMP. Ticket index 24.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-01T20:00:00',
        timestamptz '2024-03-05T20:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5025',
        'B3',
        'BUG',
        'SIEM use case: impossible travel — tuning needed',
        'Details for SIEM use case: impossible travel — tuning needed. Tracked under sample seed SMP. Ticket index 25.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-03T09:00:00',
        timestamptz '2024-03-08T09:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5026',
        'B1',
        'TASK',
        'Vendor SOC2 report overdue for critical supplier',
        'Details for Vendor SOC2 report overdue for critical supplier. Tracked under sample seed SMP. Ticket index 26.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-05T10:00:00',
        timestamptz '2024-03-06T10:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5027',
        'B1',
        'STORY',
        'IDS signature update failed on remote office sensor',
        'Details for IDS signature update failed on remote office sensor. Tracked under sample seed SMP. Ticket index 27.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-07T11:00:00',
        timestamptz '2024-03-09T11:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5028',
        'B2',
        'INCIDENT',
        'Password spray attempt against VPN portal',
        'Details for Password spray attempt against VPN portal. Tracked under sample seed SMP. Ticket index 28.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-09T12:00:00',
        timestamptz '2024-03-12T12:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5029',
        'B2',
        'BUG',
        'Data classification tag missing on S3 object',
        'Details for Data classification tag missing on S3 object. Tracked under sample seed SMP. Ticket index 29.',
        'Blocked',
        NULL,
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-03-11T13:00:00',
        timestamptz '2024-03-15T13:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5030',
        'B3',
        'TASK',
        'Incident comms template outdated for EU customers',
        'Details for Incident comms template outdated for EU customers. Tracked under sample seed SMP. Ticket index 30.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-13T14:00:00',
        timestamptz '2024-03-18T14:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5031',
        'B1',
        'STORY',
        'HSM firmware upgrade window scheduling',
        'Details for HSM firmware upgrade window scheduling. Tracked under sample seed SMP. Ticket index 31.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-15T15:00:00',
        timestamptz '2024-03-16T15:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5032',
        'B1',
        'INCIDENT',
        'Web app XSS in comment field — pen test finding',
        'Details for Web app XSS in comment field — pen test finding. Tracked under sample seed SMP. Ticket index 32.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-17T16:00:00',
        timestamptz '2024-03-19T16:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5033',
        'B2',
        'BUG',
        'Log retention policy not applied to new index',
        'Details for Log retention policy not applied to new index. Tracked under sample seed SMP. Ticket index 33.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-19T17:00:00',
        timestamptz '2024-03-22T17:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5034',
        'B2',
        'TASK',
        'MDM profile push failing on enrolled iPads',
        'Details for MDM profile push failing on enrolled iPads. Tracked under sample seed SMP. Ticket index 34.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-21T18:00:00',
        timestamptz '2024-03-25T18:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5035',
        'B3',
        'STORY',
        'Database audit logging gap during maintenance',
        'Details for Database audit logging gap during maintenance. Tracked under sample seed SMP. Ticket index 35.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-23T19:00:00',
        timestamptz '2024-03-28T19:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5036',
        'B1',
        'INCIDENT',
        'Supply chain alert on compromised npm package',
        'Details for Supply chain alert on compromised npm package. Tracked under sample seed SMP. Ticket index 36.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-03-25T20:00:00',
        timestamptz '2024-03-26T20:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5037',
        'B1',
        'BUG',
        'Zero trust agent crash loop on Windows 11',
        'Details for Zero trust agent crash loop on Windows 11. Tracked under sample seed SMP. Ticket index 37.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-27T09:00:00',
        timestamptz '2024-03-29T09:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5038',
        'B2',
        'TASK',
        'GDPR DSAR export timeout for large mailboxes',
        'Details for GDPR DSAR export timeout for large mailboxes. Tracked under sample seed SMP. Ticket index 38.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-03-29T10:00:00',
        timestamptz '2024-04-01T10:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5039',
        'B2',
        'STORY',
        'C2 traffic pattern on isolated lab subnet',
        'Details for C2 traffic pattern on isolated lab subnet. Tracked under sample seed SMP. Ticket index 39.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-03-31T11:00:00',
        timestamptz '2024-04-04T11:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5040',
        'B3',
        'INCIDENT',
        'Certificate pinning break after CDN migration',
        'Details for Certificate pinning break after CDN migration. Tracked under sample seed SMP. Ticket index 40.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-02T12:00:00',
        timestamptz '2024-04-07T12:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5041',
        'B1',
        'BUG',
        'Brute force lockout not syncing across regions',
        'Details for Brute force lockout not syncing across regions. Tracked under sample seed SMP. Ticket index 41.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-04-04T13:00:00',
        timestamptz '2024-04-05T13:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5042',
        'B1',
        'TASK',
        'Vulnerability scan false negative on OpenSSL',
        'Details for Vulnerability scan false negative on OpenSSL. Tracked under sample seed SMP. Ticket index 42.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-06T14:00:00',
        timestamptz '2024-04-08T14:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5043',
        'B2',
        'STORY',
        'Segregation of duties gap in payment approvals',
        'Details for Segregation of duties gap in payment approvals. Tracked under sample seed SMP. Ticket index 43.',
        'Open',
        NULL,
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-04-08T15:00:00',
        timestamptz '2024-04-11T15:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5044',
        'B2',
        'INCIDENT',
        'Cloud IAM key rotation overdue by 90 days',
        'Details for Cloud IAM key rotation overdue by 90 days. Tracked under sample seed SMP. Ticket index 44.',
        'In Progress',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-04-10T16:00:00',
        timestamptz '2024-04-14T16:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5045',
        'B3',
        'BUG',
        'Phishing simulation click rate above threshold',
        'Details for Phishing simulation click rate above threshold. Tracked under sample seed SMP. Ticket index 45.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-12T17:00:00',
        timestamptz '2024-04-17T17:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5046',
        'B1',
        'TASK',
        'Network segmentation exception for legacy app',
        'Details for Network segmentation exception for legacy app. Tracked under sample seed SMP. Ticket index 46.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-14T18:00:00',
        timestamptz '2024-04-15T18:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5047',
        'B1',
        'STORY',
        'SIEM parser error on custom application logs',
        'Details for SIEM parser error on custom application logs. Tracked under sample seed SMP. Ticket index 47.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-04-16T19:00:00',
        timestamptz '2024-04-18T19:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5048',
        'B2',
        'INCIDENT',
        'Red team finding: lateral movement via RDP',
        'Details for Red team finding: lateral movement via RDP. Tracked under sample seed SMP. Ticket index 48.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-18T20:00:00',
        timestamptz '2024-04-21T20:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5049',
        'B2',
        'BUG',
        'Customer PII in application error stack traces',
        'Details for Customer PII in application error stack traces. Tracked under sample seed SMP. Ticket index 49.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-04-20T09:00:00',
        timestamptz '2024-04-24T09:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5050',
        'B3',
        'TASK',
        'Backup encryption key custodian on leave',
        'Details for Backup encryption key custodian on leave. Tracked under sample seed SMP. Ticket index 50.',
        'In Progress',
        NULL,
        '[{"author": "soc-analyst", "body": "Escalated to engineering for review."}]'::jsonb,
        timestamptz '2024-04-22T10:00:00',
        timestamptz '2024-04-27T10:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5051',
        'B1',
        'STORY',
        'App gateway rate limit bypass via header spoof',
        'Details for App gateway rate limit bypass via header spoof. Tracked under sample seed SMP. Ticket index 51.',
        'Resolved',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-24T11:00:00',
        timestamptz '2024-04-25T11:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5052',
        'B1',
        'INCIDENT',
        'Threat intel feed stale since weekend outage',
        'Details for Threat intel feed stale since weekend outage. Tracked under sample seed SMP. Ticket index 52.',
        'Closed',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-26T12:00:00',
        timestamptz '2024-04-28T12:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5053',
        'B2',
        'BUG',
        'SAML assertion replay in test environment',
        'Details for SAML assertion replay in test environment. Tracked under sample seed SMP. Ticket index 53.',
        'Blocked',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-04-28T13:00:00',
        timestamptz '2024-05-01T13:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5054',
        'B2',
        'TASK',
        'Disk encryption not enforced on contractor laptops',
        'Details for Disk encryption not enforced on contractor laptops. Tracked under sample seed SMP. Ticket index 54.',
        'Awaiting Customer',
        'Mitigation documented; verified in staging.',
        '[]'::jsonb,
        timestamptz '2024-04-30T14:00:00',
        timestamptz '2024-05-04T14:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    ),
    (
        'SMP-5055',
        'B3',
        'STORY',
        'Container escape PoC in non-prod cluster',
        'Details for Container escape PoC in non-prod cluster. Tracked under sample seed SMP. Ticket index 55.',
        'Open',
        NULL,
        '[]'::jsonb,
        timestamptz '2024-05-02T15:00:00',
        timestamptz '2024-05-07T15:00:00',
        ('[1' || repeat(',0', 767) || ']')::vector,
        NULL
    )
ON CONFLICT (jira_id) DO NOTHING;